### ISSUE TITLE
I'm receiving "None" instead of some data in additional data

### ISSUE THREAD

**Issue by tirli** [getsentry/sentry#12014]
Hi. I'm using 
```
"raven-for-redux": "^1.3.1",
"raven-js": "^3.26.3"
```
and getting additional data in that format:
```
{
    errors: [None],
    isValid: False,
}
```
 The problem is that for the same kind of errors a couple of weeks ago I was receiving concrete data instead of None. What is more, old issues now also show "None" instead of data that was there. 

I haven't found anything in docs or issues except or maybe #2556 But it's not null there. 

Has something changed in displaying of errors?

**Comment by untitaker** [comment]
Hi, yes, we're fixing this as we speak :)

**Comment by untitaker** [comment]
This needs to be deployed: https://github.com/getsentry/semaphore/pull/174

We recently rolled out a rewrite of all the normalization, validation and trimming code.

**Comment by untitaker** [comment]
Should be fixed

**Comment by tirli** [comment]
Will it be fixed only for new issues? Because I still see None. Or it's not deployed yet?

**Comment by untitaker** [comment]
It will be fixed only for new events. If one your users encounters the same error again, you should see their data again.
