### ISSUE TITLE
LegacyBrowsersFilter#get_user_agent 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by felixbuenemann** [getsentry/sentry#14892]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [briefly describe your environment]

On-Premise 9.1.2 via virtualenv, NGINX, uwsgi, Python 2.7.12 on Ubuntu 16.04 x86_64.

## Description

There is a regression in `LegacyBrowsersFilter#get_user_agent` that happens after upgrading from 9.1.1 to 9.1.2:

> 'NoneType' object is not iterable

See: https://sentry.louis-net.de/share/issue/0e18e75358fc4712a5b8b1761d30b9c4/

The problem is that the method only captures `LookupError`, which was fine in 9.1.1, where the code used `for key, value in data['request']['headers']` ([source](https://github.com/getsentry/sentry/blob/9.1.1/src/sentry/filters/legacy_browsers.py#L82)), but in 9.1.2 this has changed to `for key, value in get_path(data, 'request', 'headers', filter=True)` ([source](https://github.com/getsentry/sentry/blob/9.1.2/src/sentry/filters/legacy_browsers.py#L83)), which returns `None` if the path cannot be found ([see get_path source](https://github.com/getsentry/sentry/blob/9.1.2/src/sentry/utils/safe.py#L127)).

### Possible Solution

The code needs to be modified to check for the `None` return value and remove the `LookupError` handling, since it makes no sense with `get_path`.

Another solution would be to revert the method to the 9.1.1 version, since it already handled errors.

The regression was introduced in d8c20f81f667f9ea2aa09d9c76876b2e1bd5b445 as part of #12637.

**Comment by felixbuenemann** [comment]
Locally I fixed the problem by reverting to the previous version:

```diff
diff --git a/src/sentry/filters/legacy_browsers.py b/src/sentry/filters/legacy_browsers.py
index 531fbbaa4a..789d0d10cd 100644
--- a/src/sentry/filters/legacy_browsers.py
+++ b/src/sentry/filters/legacy_browsers.py
@@ -82,7 +82,7 @@ class LegacyBrowsersFilter(Filter):

     def get_user_agent(self, data):
         try:
-            for key, value in get_path(data, 'request', 'headers', filter=True):
+            for key, value in data['request']['headers']:
                 if key.lower() == 'user-agent':
                     return value
         except LookupError:
```

**Comment by BYK** [comment]
This is fixed on master: https://github.com/getsentry/sentry/pull/12645

Quite unfortunate that this didn't make it into 9.1.2 :(

**Comment by felixbuenemann** [comment]
@BYK Thanks for the update.

Looks like that fix is still missing from the `release/9.1.x` branch.

Will there be no more 9.1.x releases?

**Comment by BYK** [comment]
@felixbuenemann we are not planning to release another 9.1.x release. Our eyes are set on the upcoming v10 release, hopefully just before the new year.
