### ISSUE TITLE
GitHub OAuth broken in 20.10.1

### ISSUE THREAD

**Issue by raoul-thill** [getsentry/sentry#21664]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 20.10.1

## Description

GitHub authentication integration is broken in 20.10.1
Before I used 20.9.1 which works fine with GitHub OAuth2 provider, but in the most recent release I can no longer login using the sole enabled method of GitHub login.
After downgrade to 20.9.1 everything worked again.

In the log files nothing is visible, only error in browser is saying client_id/client_secret incorrect.

The only information visible in the log files is the following deprecation warning:
```
web_1                          | /usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py:197: DeprecatedSettingWarning: The GITHUB_APP_ID setting is deprecated. Please use SENTRY_OPTIONS['github-login.client-id'] instead.
web_1                          |   warnings.warn(DeprecatedSettingWarning(options_mapper[k], "SENTRY_OPTIONS['%s']" % k))
web_1                          | /usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py:197: DeprecatedSettingWarning: The GITHUB_API_SECRET setting is deprecated. Please use SENTRY_OPTIONS['github-login.client-secret'] instead.
web_1                          |   warnings.warn(DeprecatedSettingWarning(options_mapper[k], "SENTRY_OPTIONS['%s']" % k))
web_1                          | /usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py:197: DeprecatedSettingWarning: The GITHUB_EXTENDED_PERMISSIONS setting is deprecated. Please use SENTRY_OPTIONS['github-login.extended-permissions'] instead.
web_1                          |   warnings.warn(DeprecatedSettingWarning(options_mapper[k], "SENTRY_OPTIONS['%s']" % k))
```

I tried this configuration as well, but did not work either.

**Comment by BYK** [comment]
Pretty sure you are using Python 3 version of Sentry. There was a bug that was fixed with #21508. If that's the case you can upgrade to the latest nightly to get the fix, wait till 20.11.0 to be released with the fix or switch back to the Python 2 version at your own risk.

If this is not the issue, we'd need more logs and your configuration.

**Comment by raoul-thill** [comment]
Thanks @BYK, I will wait for the 20.11.0 release and in case the error is still present I update the issue with configuration and logs.
