### ISSUE TITLE
Unable to activate education plan due to missing CSRF token

### ISSUE THREAD

**Issue by brigaccess** [getsentry/sentry#22150]
## Important Details

How are you running Sentry?

- [ ] On-Premise w/ Docker, version x.y.z

- [x] Saas (sentry.io)

- [ ] Other, version x.y.z, [briefly describe your environment]

## Description

When activating education plan with Github student pack, POST request that activates it fails with "CSRF Failed: CSRF token missing or incorrect."

## Steps to Reproduce

1. Open https://sentry.io/for/education/
2. Go through the activation process to step 3 ("Activate plan" button)
3. Click the button

### What you expected to happen

Academic plan activation.

### Possible Solution

Probably send CSRF token in request body?

**Comment by BYK** [comment]
@EvanPurkhiser could this be related to your recent work on forms?

**Comment by w0rng** [comment]
I have the same problem in Edge and FireFox browsers.

**Comment by EvanPurkhiser** [comment]
Yes thank you for reporting this. It was difficult to test since I’m no longer a student 🙃

**Comment by EvanPurkhiser** [comment]
This should be fixed now :)

**Comment by w0rng** [comment]
> This should be fixed now :)

Yes, I don't get CSRF errors anymore. I started getting errors with code `400 Bad Request` :)

The server sends a response to `organization: ["this field is required."]`

**Comment by ZusorCode** [comment]
@EvanPurkhiser I still can't activate the pack.
Previously I got the error "Failed to activate education plan. Please try again." and now [this happens](https://i.imgur.com/zJF6bFf.gif) whenever I try to activate the pack
