### ISSUE TITLE
Date filter resets when viewing a concrete release from URL

### ISSUE THREAD

**Issue by juraj-blahunka** [getsentry/sentry#23324]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 20.12.1 (bade073)

## Description

When viewing a concrete release and selecting a date filter (e.g. **Last 7 days**), the page loads correctly. Reloading the page or opening the page from URL resets the filter.

## Steps to Reproduce

1. Open a concrete release page (open Releases and select a release)
2. Choose an option from the date filter (e.g. Last 7 days) - observe that the query changes to `&statsPeriod=7d`
3. The UI refreshes accordingly
4. Copy the URL from the navigation bar
5. Reload the page
6. The page redirects to query with `?end=2021-01-25T20%3A01%3A27&start=2021-01-24T20%3A01%3A27` which doesn't respect the original date filter.

1. Paste and open the URL from previous step 4.
2. Observe the same redirect to query with `?end=2021-01-25T20%3A01%3A27&start=2021-01-24T20%3A01%3A27`
3. and so on.

### What you expected to happen

The date filter should persist when reloading a release page or opening the page from URL.

I couldn't reproduce the issue on the Releases page or Issues page.

**Comment by BYK** [comment]
Got word that this should be fixed on master (and possibly on 21.1.0 release). Mind giving it a try?

**Comment by juraj-blahunka** [comment]
Still an issue on 21.1.0, didn't have a  chance to test master.

**Comment by juraj-blahunka** [comment]
Likely still a bug. We're still on `21.1.0`. I'll share info again once we upgrade to a newer version.

**Comment by MichaelSun48** [comment]
Closing this one out due to lack of response and >3 years of inactivity. Please feel free to reopen if you're still experiencing this!
