### ISSUE TITLE
Unable to finish upgrade command in docker on Digital Ocean

### ISSUE THREAD

**Issue by 3ka5-cat** [getsentry/sentry#3635]
Trying to launch official docker image (https://hub.docker.com/_/sentry/) on digital ocean ubuntu trusty with docker 1.11.2 (locally it works):
`docker run -d --name redis redis`
`docker run -d --name sentry-postgres postgres`
But `docker run -it -e SENTRY_SECRET_KEY=${SECRET_KEY} --link sentry-postgres:postgres --link redis:redis sentry upgrade` occasionally stops while applying migrations, like:

```
 > sentry:0177_fill_member_counters
 > sentry:0178_auto__del_unique_organizationmember_organization_counter
 > sentry:0179_auto__add_field_release_date_released
user@host:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
237374b4ccba        postgres            "/docker-entrypoint.s"   About a minute ago   Up About a minute   5432/tcp            sentry-postgres
5647fcd3b04b        redis               "docker-entrypoint.sh"   About a minute ago   Up About a minute   6379/tcp            redis
```

`docker logs sentry-postgres` shows:
```
ERROR:  relation "sentry_option" does not exist at character 114
STATEMENT:  SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."key" = 'system.url-prefix' 
ERROR:  operator does not exist: json = json at character 19
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT '{}'::json = '{}'::json;
ERROR:  operator does not exist: json = json at character 19
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT '{}'::json = '{}'::json;
ERROR:  operator does not exist: json = json at character 19
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT '{}'::json = '{}'::json;
ERROR:  operator does not exist: json = json at character 19
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT '{}'::json = '{}'::json;
ERROR:  operator does not exist: json = json at character 19
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT '{}'::json = '{}'::json;
ERROR:  operator does not exist: json = json at character 19
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  SELECT '{}'::json = '{}'::json;
```
If re-launch same command then migration starts from last completed migration and keep going, until suddenly don't stop again. Finally, when all migrations are applied, container doesn't create internal sentry project and doesn't ask to create user.

Any ideas what could be wrong?

**Comment by mattrobenolt** [comment]
No idea. Are you possibly running out of memory and the process is crashing? I've seen weird results because of that.

**Comment by 3ka5-cat** [comment]
@mattrobenolt yep, seems so. Will move to other host. Could you please advice how much memory would be enough for full setup (potsgres, redis, sentry, worker, scheduler) ?

**Comment by mattrobenolt** [comment]
All on the same machine? You'd likely want at minimum 2G, but that won't go very far. It'd be fine for super low volumes of data. But beyond that, you're going to have problems very quickly.

**Comment by PegasusWang** [comment]
Also meet similar problem, solved by releasing some memory.The hint message "ERROR:  relation "sentry_option" does not exist at character 114" is weird and can not provide any useful debug information.

**Comment by mattrobenolt** [comment]
The problem is, the process crashes because it OOM'd. There's not anything really we can do here to detect that hostile environment.

**Comment by Nikhil-Shenoy** [comment]
I've run into the same issue as well, and after doing cleanup steps recommended [here](http://blog.yohanliyanage.com/2015/05/docker-clean-up-after-yourself/), I still get this same error. Has anyone else figured out a way to get around this?

**Comment by annaswims** [comment]
Can confirm that a fresh install on a vagrant box with 2048MB of memory fails during migrations and that bumping memory to 3072 did the trick.
