### ISSUE TITLE
Jira Integration shows contradicting states in the UI

### ISSUE THREAD

**Issue by RobinCsl** [getsentry/sentry#43425]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/settings/kiwicom/integrations/jira/

### Steps to Reproduce

1. Go to Integrations settings screen
   Jira appears to be _Not Installed_. 
![Screenshot 2023-01-19 at 12 56 16](https://user-images.githubusercontent.com/22741774/213437353-ac52a9c5-e13c-462a-86ef-ef38d72aefed.png)

2. Click on the Jira integration to configure it.
  Jira appears to be _Installed_ and the specific integration is shown as _Enabled_.
![Screenshot 2023-01-19 at 12 56 29](https://user-images.githubusercontent.com/22741774/213437508-2f5d8120-e94a-451a-ac01-2c4b449b7f4d.png)

Could you please look into it?
Many thanks!

### Expected Result

The Jira integration state is coherent across the UI.

Jira being _Installed_ and the integration being shown as _Enabled_ should mean the whole integration works as expected.

### Actual Result

When on the issue view and trying to link to a Jira ticket, it is not possible to link to Jira. Nothing Jira related is present in the UI.
![Screenshot 2023-01-19 at 13 01 42](https://user-images.githubusercontent.com/22741774/213437929-71386367-3dec-4613-8415-29a4e093e46a.png)

When trying to access Sentry-related information from Jira, we obtain an error message as shown in the screenshot below.
![Screenshot 2023-01-19 at 13 02 52](https://user-images.githubusercontent.com/22741774/213438143-b9ae021d-c8fc-4b17-a1f4-59e2b3f760ac.png)

Note: the integration was working at some point (at least until January, 9th, 2023) and it stopped working recently (sadly, we didn't realise this immediately, so I cannot be more precise).

**Comment by snigdhas** [comment]
Hi @RobinCsl, thanks for filing this. We're aware of the issue and are working to resolve it.

**Comment by snigdhas** [comment]
#43458 should fix this

**Comment by RobinCsl** [comment]
Hi @snigdhas, thanks for the update!

Am I right in assuming the fix hasn't been deployed yet? 

It seems the issue persists on my side.

**Comment by snigdhas** [comment]
Hi @RobinCsl, that's correct. #43458 is still under review.
