### ISSUE TITLE
Settings/Notifications page unable to load

### ISSUE THREAD

**Issue by matticus1181** [getsentry/sentry#4349]
When I try to go to the settings/notifications page, it gives me page not found

**Comment by dcramer** [comment]
fixed in 8a925f35ba26ac6af30e0c12dbd9f8eee8c7a952

**Comment by matticus1181** [comment]
This isn't fixed.

When I click on "Set up a notification service", it takes me to a page where I select the project. After I do that, I get a "page not found".  The route may have been changed, but the link to it, has not.

**Comment by dcramer** [comment]
@matticus1181 changes are not instantly deployed upon merging. Its under "Alerts" in your project settings. We fixed the link and when it gets deployed it'll be reflected in production.
