### ISSUE TITLE
Allows cors on ingest.sentry.io

### ISSUE THREAD

**Issue by Amatewasu** [getsentry/sentry#49535]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add same origin headers (`Cross-Origin-Opener-Policy: same-origin` and `Cross-Origin-Embedder-Policy: require-corp`)
2. Call `Sentry.showReportDialog`
3. The request is blocked by the browser because it lacks cors headers on the server (`Access-Control-Allow-Origin: *` for example)
4. The user feedback dialog is therefore not shown to the user

### Expected Result

- Not block the request
- Display the user feedback dialog to the user

### Actual Result

The request is blocked by the browser:
`"GET https://o1127159.ingest.sentry.io/api/embed/error-page/?dsn=https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371&eventId=71e2f933bbb84e07828a4e6ed073ca34&title=Report%20an%20issue&name=NAME OF THE USER*&email=EMAIL OF THE USERnet::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 302"`

For your information, following the previously mentioned error, I tried to hijack by inserting directly the Sentry's loaded script with the following piece of code:
```ts
const scriptSentryId = 'sentry-error-embed';
const scriptSentryEls = document.querySelectorAll(`#${scriptSentryId}`);
scriptSentryEls.forEach((scriptSentryEl) => {
  if (scriptSentryEl instanceof HTMLElement) {
    scriptSentryEl.remove();
  }
});

const username = profile && 'name' in profile ? profile.name : undefined;
const email = profile && 'email' in profile ? profile.email : undefined;
const urlSentryReport = `https://sentry.io/api/embed/error-page/?dsn=https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371&eventId=${event.event_id}&title=Report%20an%20issue&name=${username}&email=${email}`;
const scriptShowReportDialog = document.createElement('script');
scriptShowReportDialog.id = scriptSentryId;
scriptShowReportDialog.type = 'text/javascript';
scriptShowReportDialog.async = true;
scriptShowReportDialog.crossOrigin = 'anonymous';
scriptShowReportDialog.referrerPolicy = 'no-referrer';
scriptShowReportDialog.src = urlSentryReport;
document.body.appendChild(scriptShowReportDialog);
```
but the request is also blocked by the browser:
`
Access to script at 'https://sentry.io/api/embed/error-page/?dsn=https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371&eventId=b8b588b0bb014590adfb6f93de24550f&title=Report%20an%20issue&name=undefined&email=undefined' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.  
GET https://sentry.io/api/embed/error-page/?dsn=https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371&eventId=b8b588b0bb014590adfb6f93de24550f&title=Report%20an%20issue&name=undefined&email=undefined net::ERR_FAILED 200 (OK)
`

### Product Area

User Feedback

### Link

(can be provided on request but is not publicly available)

### DSN

https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371

**Comment by JoshFerge** [comment]
seems like we need to add `Cross-Origin-Resource-Policy: cross-origin` to our error page response https://github.com/getsentry/sentry/blob/7d84829c2111305cd220b9ef1d482964b7bb45ad/src/sentry/web/frontend/error_page_embed.py#L230 , but need to do more digging on what's correct / implications. https://web.dev/why-coop-coep/

**Comment by Amatewasu** [comment]
Hello, do you have any updates regarding this issue? Thank you!

**Comment by lforst** [comment]
Just opened a PR to fix this https://github.com/getsentry/sentry/pull/51138

**Comment by Amatewasu** [comment]
Thank you a lot for the work!

By any chance, do you know when this change will be live?

**Comment by lforst** [comment]
@Amatewasu It is live since two weeks. Are you still facing problems?

**Comment by Amatewasu** [comment]
@lforst I just tested and I am still facing the issue.

In my JS browser console:
```main.48957e68.js:2     GET https://o1127159.ingest.sentry.io/api/embed/error-page/?dsn=https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371&eventId=e192e042fadc4ef7913fc88bef551dbc&title=Report%20an%20issue&name=`my_first_name%20my_last_name&email=my%40email.com net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 302```

And in the network tab:
![image](https://github.com/getsentry/sentry/assets/747613/7b7d56b0-7356-4a9c-b9b0-493a270eb0c3)

So it looks like there no `Cross-Oirigin-Resource-Policy` header?

**Comment by lforst** [comment]
Ah interesting, I thought this is implicitly gonna be resolved by setting an `Access-Control-Allow-Origin` header.

Seems like we also need to add a `Cross-Oirigin-Resource-Policy: cross-origin` header.

**Comment by lforst** [comment]
Wait actually, shouldn't this be fixed by just setting a `crossorigin` attribute on the embedded script tag? I can see in your code snippet that you set `crossOrigin = 'anonymous'` which looks like a typo.

**Comment by Amatewasu** [comment]
@lforst Thank you for your answer. I just saw the PR you opened two weeks ago. I guess it is live now? (i am still facing the same issue)

**Comment by robert-king** [comment]
I got the same error I think when trying to showDialog

{
      provide: ErrorHandler,
      useValue: Sentry.createErrorHandler({
        showDialog: true,
      }),
    },
    
    making showDialog: false fixes the error.

    Access to script at 'https://o4505552496230400.ingest.sentry.io/api/embed/error-page/?dsn=https://721c9e37a0cd4a0e9412190604008a89@o4505552496230400.ingest.sentry.io/4505552757719040&eventId=e163e6e38ab34d9f830e145d7eb7c644' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by HansAarneLiblik** [comment]
@lforst Upgrading from `@sentry/react` v7.57.0 to v7.58.1 (Where this fix(?) is included) our Sentry integration started to fail and I'm guessing these are related

> Access to script at 'https://<my-sentry>/api/embed/error-page/?dsn=https://3ce8d890043a4c558be5515de3e01d09@<my-sentry>/2&eventId=efc303799d1844d4bab7128fb52be69a&name=<username>&email=<email>' from origin 'https://<my-application>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by lforst** [comment]
@Amatewasu Did you upgrade to the newest SDK version?

@robert-king What SDK version are you on?

@HansAarneLiblik what self-hosted version are you on?

**Comment by Amatewasu** [comment]
@lforst I did not. Here's my current package.json:
```
"@sentry/cli": "^2.7.0",
"@sentry/integrations": "^7.16.0",
"@sentry/react": "^7.16.0",
"@sentry/rrweb": "^0.3.3",
"@sentry/tracing": "^7.16.0",
```
I will update the SDK and let you know about the result. Thanks!

**Comment by Amatewasu** [comment]
@lforst I just updated my package.json and tested on an online development environment and I still get the issue.

Here's the screenshot of the error:
![Screenshot of the error](https://github.com/getsentry/sentry/assets/747613/aa7a6f32-280b-4593-9f35-47713d78b658)

My new package.json (of course I've ran `npm install` after the update):
```
"@sentry/cli": "2.19.4",
"@sentry/integrations": "^7.60.0",
"@sentry/react": "^7.60.0",
"@sentry/rrweb": "^0.3.3",
"@sentry/tracing": "^7.60.0",
```

(I can give you access to the page to reproduce if needed)

**Comment by lforst** [comment]
@Amatewasu do you mind sharing the full URL inside the first error?

I am a bit weirded out because we are setting the `Access-Control-Allow-Origin` header in any case to `*` now...

**Comment by lforst** [comment]
@Amatewasu another question. Is this happening inside an iframe?

**Comment by Amatewasu** [comment]
> @Amatewasu do you mind sharing the full URL inside the first error?

Sure, I have sent you an email.

> I am a bit weirded out because we are setting the `Access-Control-Allow-Origin` header in any case to `*` now...

It looks like all the `https://o1127159.ingest.sentry.io/api/6417371/envelope/?sentry_key=*` requests have properly the `Access-Control-Allow-Origin` header but not the request `https://o1127159.ingest.sentry.io/api/embed/error-page/?dsn=...`.





> @Amatewasu another question. Is this happening inside an iframe?

It is not happening inside an iframe. :)

**Comment by Amatewasu** [comment]
> @Amatewasu do you mind sharing the full URL inside the first error?

The full URL is: `https://o1127159.ingest.sentry.io/api/embed/error-page/?dsn=https://8f845bb769e24d9eb37a25bfd63b9c96@o1127159.ingest.sentry.io/6417371&eventId=ca9ebacd763e4ca99bb0032b7ba2742d&title=Report%20an%20issue&name=Alexis%20DELRIEU&email=alexis.delrieu%40balyo.com`

**Comment by robert-king** [comment]
"@sentry/angular-ivy": "^7.59.2",
"@sentry/cli": "^2.19.4",
"@sentry/webpack-plugin": "^2.4.0",

this was testing from localhost i think. (http to https).

**Comment by HansAarneLiblik** [comment]
@lforst Our self-hosted sentry is on version 23.3.1. If I remember correctly, we can't upgrade to the next version without upgrading our postgres database before

**Comment by timkelty** [comment]
@lforst I am experiencing the same CORS error with the error page, meaning I can't get User Feedback working at all.

It happens when attempting to call `Sentry.showReportDialog()`

**Details:**
- URL: https://o4505162248945664.ingest.sentry.io/api/embed/error-page/?dsn=https://1d71f704d08d4bad95a66d041a087279@o4505162248945664.ingest.sentry.io/4505517755138048&eventId=077c1b8eb117497fb739bb7a86d575e7
- package versions (just updated):
  - @sentry/vue@7.60.1
  - @sentry/browser@7.60.1
- inside iframe: no
- `Project -> Allowed Domains` in Sentry dashboard has my domain added.

**Comment by timkelty** [comment]
UPDATE – @lforst I think the issue is indeed the redirect response missing the `Access-Control-Allow-Origin` header. As a test, I replaced the URL with the `https://sentry.io` domain it was 302ing to and the request worked.

**Comment by kerenkhatiwada** [comment]
@lforst Sharing the [ZD ticket](https://sentry.zendesk.com/agent/tickets/99353) @timkelty has wrote in case it is needed.

**Comment by chadwhitacre** [comment]
Reopening since this seems to be ongoing.

**Comment by roggenkemper** [comment]
@lforst

**Comment by lforst** [comment]
Hi, there is currently a deploy to Sentry going out that will attach a `Access-Control-Allow-Origin: *` header to the redirect response coming from `*.ingest.sentry.io`.

In my test app, this finally fixed the issue. Feel free to let me know in case this still seems to be a problem.

**Comment by Amatewasu** [comment]
@lforst The issue is fixed in my app. Thanks a lot!

**Comment by timkelty** [comment]
@lforst This has fixed the CORS errors for me, but I now get:

```
Refused to execute script from 'https://sentry.io/api/embed/error-page/?dsn=https://1d71f704d08d4bad95a66d041a087279@o4505162248945664.ingest.sentry.io/4505517755138048&isTrusted=true&_vts=1690860543286&eventId=undefined&pointerId=1&width=1&height=1&pressure=0&tiltX=0&tiltY=0&azimuthAngle=0&altitudeAngle=1.5707963267948966&tangentialPressure=0&twist=0&pointerType=mouse&isPrimary=false&getCoalescedEvents=function%20getCoalescedEvents()%20%7B%20%5Bnative%20code%5D%20%7D&getPredictedEvents=function%20getPredictedEvents()%20%7B%20%5Bnative%2...5Bobject%20SVGSVGElement%5D&returnValue=true&cancelBubble=false&NONE=0&CAPTURING_PHASE=1&AT_TARGET=2&BUBBLING_PHASE=3&composedPath=function%20composedPath()%20%7B%20%5Bnative%20code%5D%20%7D&initEvent=function%20initEvent()%20%7B%20%5Bnative%20code%5D%20%7D&preventDefault=function%20preventDefault()%20%7B%20%5Bnative%20code%5D%20%7D&stopImmediatePropagation=function%20stopImmediatePropagation()%20%7B%20%5Bnative%20code%5D%20%7D&stopPropagation=function%20stopPropagation()%20%7B%20%5Bnative%20code%5D%20%7D' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

… I believe because of the `nosniff` headers being returned.

It looks like that has been previously reported here: https://github.com/getsentry/sentry-javascript/issues/1439

**Comment by timkelty** [comment]
@lforst done – https://github.com/getsentry/sentry/issues/53952

**Comment by HansAarneLiblik** [comment]
@lforst I'm a bit confused.

* My self-hosted Sentry server was always at the same version `23.3.1`
* Tried to upgrade my `@sentry/react` from version `7.57.0`

And now i'm faced with this CORS error.

> Access to script at 'https://\<my-sentry-server>/api/embed/error-page/?dsn=https://\<key>@\<my-sentry-server>/2&eventId=456a47141e2c4ecda4c2145f3aaaddb9&name=\<name>&email=\<email>' from origin 'https://\<my-client>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is my only solution to ALSO upgrade my Sentry server?

**Comment by lforst** [comment]
> Is my only solution to ALSO upgrade my Sentry server?

@HansAarneLiblik yes
