### ISSUE TITLE
Unable to create separate alerts with same THEN condition but different Environments

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#55459]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an alert and select an environment in Step 1 
<img width="882" alt="Screenshot 2023-08-30 at 10 08 05 AM" src="https://github.com/getsentry/sentry/assets/96670625/651d9aa6-4530-4204-b398-40e61574dd6e">

2. Set a THEN condition and save the alert [Direct link to alert that can be tested on](https://francisorg.sentry.io/alerts/rules/bundlers/14635888/details/)

3. Click on Duplicate and change the environment
<img width="851" alt="Screenshot 2023-08-30 at 10 10 58 AM" src="https://github.com/getsentry/sentry/assets/96670625/e257a35f-b66c-4498-a4d3-b45983577bb1">

4. Try to save and receive error
<img width="707" alt="Screenshot 2023-08-30 at 10 19 21 AM" src="https://github.com/getsentry/sentry/assets/96670625/e94fdaa3-e4d0-46ee-8f13-b256e65b9573">

### Expected Result

Should be able to create a separate alert with a separate environment

### Actual Result

Unable to create duplicate alerts with different environments and even with a different alert name.

### Product Area

Alerts

**Comment by scttcper** [comment]
thanks for reporting, a fix is already on its way out #55412

**Comment by amacrobert-meq** [comment]
@scttcper Hi, I'm the original reporter. The issue described in https://github.com/getsentry/sentry/pull/55412 does not quite match the bug I reported.

https://github.com/getsentry/sentry/pull/55412 reports this being an issue only when one alert does not have the environment set, saying that's the root cause. I'm running into this issue when both alerts have an environment set.

Does that fix also fix this slightly different issue?

**Comment by scttcper** [comment]
@amacrobert-meq that should be fixed with those changes in a few minutes when it deploys.

**Comment by amacrobert-meq** [comment]
@scttcper As of 3:41pm EDT, this issue is not resolved. Same issue, both in terraform and in web UI.

Should I wait longer for a release, or is this issue indeed different?
