### ISSUE TITLE
onpremise 8.22.0 multiple broken links in project settings

### ISSUE THREAD

**Issue by YannickteK** [getsentry/sentry#6753]
Hello

I'm running the on premise 8.22.0 version. I have multiple broken links on the project settings page:
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/install/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/csp/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/user-feedback/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/filters/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/keys/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/dashboard/
http://localhost:9000/sentry/blablabla/settings/sentry/blablablap/releases/
http://localhost:9000/sentry/blablabla/settings/sentry/blablabla/settings/alerts/
http://localhost:9000/sentry/blablabla/settings/tags/sentry/blablabla/settings/processing-issues/

**Comment by billyvg** [comment]
@YannickteK I believe this was fixed in https://github.com/getsentry/sentry/pull/6386

**Comment by cajbecu** [comment]
same here

**Comment by a-hab** [comment]
I can still reproduce this bug on premise 8.22.0. Any updates?

**Comment by alternativshik** [comment]
same in 9.1.0

**Comment by BYK** [comment]
Closing due to staleness and 8.22 is not even a thing anymore.

@alternativshik - Please file a new issue with some logs to the [getsentry/onpremise](https://github.com/getsentry/onpremise) repo if you are still having this issue.
