### ISSUE TITLE
[Replays] Duplicating elements when viewing Replays in Ui

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#68731]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a user.

When viewing replays in our Ui, sometimes elements can start duplicating.  Link to replay provided by the user in linked Jira ticket.  Sometimes the elements display properly but seems to break again later.  Attaching screenshots of the behavior in Jira as well.

In linked replay - starts at around 18:44 of the replay.  Interaction with the slider causes buttons below it to start duplicating in the direction where the slider is being dragged.

[Linked Jira Ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2142)

### Expected Result

Elements should not duplicate

### Actual Result

Duplication

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2142) by [Unito](https://www.unito.io)

**Comment by aaronjensen** [comment]
I'm seeing this too. It's good to know that it's a problem with the viewer. It's also inconsistent. If I refresh the replay page, sometimes it doesn't happen anymore.

**Comment by bruno-garcia** [comment]
Thanks for letting us known @aaronjensen. Do you have a link to an example Replay you could share?

**Comment by bruno-garcia** [comment]
Seems like it's an rrweb bug: 
* https://github.com/rrweb-io/rrweb/issues/1449

**Comment by aaronjensen** [comment]
I've supplied a few replays to support. With regards to it being an rrweb bug, I don't really know how to respond to that. I don't pay for rrweb, I pay for Sentry, so I kind of have to assume that the origin doesn't matter -- it's a Sentry bug to Sentry's customers, right?

**Comment by billyvg** [comment]
We use GitHub for tracking development work, he's just adding context to the issue, not asking anything of you.

**Comment by aaronjensen** [comment]
Sounds good, thanks!

**Comment by billyvg** [comment]
Unassigning myself for now, I won't be able to take this on until mid-July at the earliest

**Comment by joshua-webdev** [comment]
My team is experiencing something like this as well, in many session replays. The problem seems to get worse as you approach the end of the replay. I'm surprised there's been no movement on this since April - the feature is basically unusable if you can't see what's happening in the recording.

**Comment by billyvg** [comment]
@joshua-webdev Can you email me some example replays that show this? `billy at sentry.io` -- we've made some fixes in other parts of the replay player, but we can take a closer look at this specifically.

**Comment by billyvg** [comment]
@joshua-webdev I did some digging around and I think this is due to a performance problem in the Breadcrumbs tab. Locally I've been able to see the replay normally when I rip out the code in question.

* Do you notice this happening on shorter replays?
* If you load the replay with the Console tab selected, does this happen as frequently?

**Comment by joshua-webdev** [comment]
I haven't seen the issue on shorter replays, usually only on replays longer than 20-30 minutes. Reloading the page with the Console tab selected does seem to make the problem go away, though.

**Comment by billyvg** [comment]
@joshua-webdev thanks for confirming, we'll look into fixing this in https://github.com/getsentry/sentry/issues/77809

**Comment by billyvg** [comment]
@joshua-webdev Sorry for the delay, but this should be fixed now, can you let us know if you're still having issues?

**Comment by joshua-webdev** [comment]
> [@joshua-webdev](https://github.com/joshua-webdev) Sorry for the delay, but this should be fixed now, can you let us know if you're still having issues?

Seems to be fixed now, thanks for resolving this!

**Comment by billyvg** [comment]
This should be resolved now -- for others that are facing similar issues, please open a new ticket.

**Comment by adamrehill** [comment]
I can open a new ticket, but just letting you know I'm still seeing this issue in replay today
