### ISSUE TITLE
[Dashboards] Release selection doesn't show all releases

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#69661]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Make sure you have created a couple of releases in Sentry
2. Go to Dashboards and select a project and 7 releases
3. Create a new widget with a Table
4. Make sure one of the columns is set to "Release (field)" and then choose another column, ie. crash_free_rate(session)

### Expected Result

All selected releases should show up in the table.

### Actual Result

Only 3 out of 7 releases show up in the table.
![Untitled](https://github.com/getsentry/sentry/assets/81985895/1d45c930-1365-4c35-99e7-164c075753cc)

If we reset the release filter, the table shows all releases normally.

Link to the dashboard [in the shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2156) as I was unable to reproduce the issue on my test org.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2156) by [Unito](https://www.unito.io)

**Comment by wmak** [comment]
Hmm I can't reproduce this at all, but I'm fairly certain I've fixed it. i'll add more details in the attached ticket

**Comment by InterstellarStella** [comment]
@wmak Can we revisit this? It looks like the issue remains on that specific dashboard. The dashboard was created through the UI, and I've attached a screenshot of the problem still occurring in the shadow ticket.

**Comment by wmak** [comment]
@InterstellarStella, the widget editor only shows 5 rows in the preview. Created widgets will show more results
