### ISSUE TITLE
Resolve in Next Version uses an older version than expected

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#69937]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. You have an issue A last seen in version 1
2. You have already got newer releases with versions 2, 3, 4, 5 in your Releases tab in Sentry, all with errors logged on other issues.
3. You resolve A in next version
4. Tap activity tab
5. See that it was resolved in versions > version 1.

I'm going to provide a video repro to y'all in our private slack channel.

### Expected Result

Resolved in versions > 5.  Next version looks at all available versions, picks the newest one, then resolves as fixed in versions > than that.

### Actual Result

Resolves in versions > than the newest version seen on the issue, rather than taking the newest version Sentry has seen in total.

### Product Area

Issues

### Link

https://dropbox.sentry.io/issues/5015533332/activity/?project=4505546600087552

**Comment by JoshFerge** [comment]
Bumping this -- another bug report has come in.

**Comment by JoshFerge** [comment]
for anyone who is interested in debugging. can run this script to create the releases and error. then do resolve in next release and you'll see. we go off of GroupRelease, so if no errors have happened in the most recent release this happens.

```
from datetime import datetime

import requests
import sentry_sdk

# Sentry API key and project details
sentry_api_key = "YOUR_SENTRY_API_KEY"
sentry_org = "YOUR_SENTRY_ORG"
sentry_project = "YOUR_SENTRY_PROJECT"

# Base URL for Sentry API
base_url = f"https://sentry.io/api/0/organizations/{sentry_org}"

# Headers for API requests
headers = {"Authorization": f"Bearer {sentry_api_key}", "Content-Type": "application/json"}

# Create releases
releases = [
    "com.joshferg.testyapp@1.31+8981",
    "com.joshferg.testyapp@1.32+8982",
    "com.joshferg.testyapp@1.33+8983",
]
for release in releases:
    release_data = {
        "version": release,
        "projects": [sentry_project],
        "ref": None,
        "url": None,
        "dateReleased": datetime.utcnow().isoformat(),
    }
    response = requests.post(f"{base_url}/releases/", headers=headers, json=release_data)
    if response.status_code == 201:
        print(f"Release {release} created successfully")
    else:
        print(f"Failed to create release {release}: {response.text}")

# Initialize Sentry SDK
sentry_sdk.init(
    dsn="https://a66b4f672f8ad38338db30bc091227e4@o19635.ingest.us.sentry.io/4507981196689408",
    release="com.joshferg.testyapp@1.31+8981",
)


def create_error():
    try:
        raise TypeError("boooooo beeeeepy")
    except TypeError as e:
        sentry_sdk.capture_exception(e)


# Create errors for release 1.31
create_error()
# create_error()

# Flush events to ensure they are sent
sentry_sdk.flush()
```

**Comment by JoshFerge** [comment]
if i were to propose a change, it would be:

https://github.com/getsentry/sentry/blob/8f78fc7d87a13d9ec40c5b0d67ae024632580ce1/src/sentry/api/helpers/group_index/update.py#L430

in here, i'd change the function to instead of grabbing the latest group release, to grab the latest semver release for the package name of the project.

**Comment by JoshFerge** [comment]
maybe we already have a helper function for this? https://github.com/getsentry/sentry/blob/8f78fc7d87a13d9ec40c5b0d67ae024632580ce1/src/sentry/models/releases/util.py#L60

**Comment by jboulter11** [comment]
That sounds like what I'm looking for.

**Comment by chrisvasselli** [comment]
The way this UI looks (see screenshot), the "next version" is described as "the next release after the current one". And right below that, it shows you an option to mark the issue as resolved in "The current release", with a version number listed. But this "current release" number is not the one that is used by "resolve in next version".

Since they both refer to the "current release", I would expect the "next version" to be the next version after the "current release" listed right below it.

![Image](https://github.com/user-attachments/assets/8ec54058-5766-40ed-a777-0187282be937)

**Comment by armenzg** [comment]
I should have a fix for this before EOW.

Are there any other organizations (besides Dropbox) in this issue that would like me to opt into the fix?

**Comment by chrisvasselli** [comment]
@armenzg Sure, I'd love access to this fix.

**Comment by armenzg** [comment]
The fix will be live in the next couple of hours for the mentioned organizations and early adopters.

**Comment by armenzg** [comment]
I will let this bake until the end of the month and then release it to everyone.
Please do let me know if you notice any issues before that.

**Comment by jboulter11** [comment]
Is this deployed to us?  My testing just now shows it's still using an old version when resolving in next version.

**Comment by jboulter11** [comment]
The fix as you described it seems like a good fix but it does not seem like it will fix the specific issue we described here.  In your PR you mention this code:

https://github.com/getsentry/sentry/blob/914c74114efdfcca7c3d5b4f29ff9308cc643bce/src/sentry/api/helpers/group_index/update.py#L145-L149

To me, these highlighted lines look exactly like the bug.  We don't want to restrict the version it's choosing as the latest version to be restricted to what's associated with the group.

**Comment by armenzg** [comment]
@jboulter11 thanks for validating 👍🏻 I have a WIP fix and will be deployed tomorrow morning

**Comment by armenzg** [comment]
@jboulter11 @chrisvasselli could you please confirm that the change fixed the issue? The fix is live for you.

**Comment by jboulter11** [comment]
This is fixed now!! 🏆 Thank you!  This is HUGE for us!

**Comment by armenzg** [comment]
> This is fixed now!! 🏆 Thank you! This is HUGE for us!

Fantastic! You're welcome!

**Comment by rustyshelf** [comment]
I'm still having this issue, or a very similar thing. In the "Resolve" Drop down I can see the latest version (1.0 Build 64):
![Image](https://github.com/user-attachments/assets/afeb1b45-6309-45e9-a97c-c921091f0ec9)

If I pick the "The Next Release" option it picks 1.0 Build 45, the oldest 1.0 release available. Does this feature require a newer release to somehow be registered in Sentry first? What I'm trying to say is "if this issue happens in a build newer than the current one, please re-open this issue". That's what I'd expect "The Next Release" to do, but it does something weirder.

**Comment by armenzg** [comment]
> I'm still having this issue, or a very similar thing. In the "Resolve" Drop down I can see the latest version (1.0 Build 64): ![Image](https://github.com/user-attachments/assets/afeb1b45-6309-45e9-a97c-c921091f0ec9)
> 
> If I pick the "The Next Release" option it picks 1.0 Build 45, the oldest 1.0 release available. Does this feature require a newer release to somehow be registered in Sentry first? What I'm trying to say is "if this issue happens in a build newer than the current one, please re-open this issue". That's what I'd expect "The Next Release" to do, but it does something weirder.

Hi @rustyshelf 
I forgot to enable the fix for early adopters. I will do so in the next couple of hours. Do you mind joining the cohort and let us know if the issue persists?

If you would rather wait, I will enable the fix to GA sometime in December.

**Comment by rustyshelf** [comment]
@armenzg all good, I can work around it until the GA. Just figured I'd mention it while it was still fresh in case it helped but sounds like you have it under control.

**Comment by armenzg** [comment]
@rustyshelf 👍🏻

**Comment by armenzg** [comment]
I will enable this for GA next week.
