### ISSUE TITLE
UI says filtering by custom tags not supported in Metric Alerts

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#76229]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create Metric Alert for errors (i.e. alert on Number of Errors)
2. Try to add a event filter using custom tags

![Image](https://github.com/user-attachments/assets/80f48d08-2f64-4bba-8211-4c230f591aee)

### Expected Result

The custom tag filter applies without the incorrect UI box

### Actual Result

The filter will apply, but our UI says that "The field xxx isn't supported here. See all searchable properties in the docs."

### Product Area

Alerts

**Comment by rachrwang** [comment]
Thanks for filing @michaelchai-sentry! Will work with the team to find time to address this

**Comment by zsperske** [comment]
Hey folks any update on this? This seriously limits what can be done with alerts.

**Comment by mifu67** [comment]
Hi @zsperskem,

This should be fixed now.

**Comment by zsperske** [comment]
@mifu67 this isn't fixed, I experienced this exact issue yesterday and someone from Sentry on our account confirmed they see the same issue.

**Comment by sdzhong** [comment]
I am following up internally (Internal Case https://www.notion.so/sentry/2428b10e4b5d80cda63dc302a8c39e2e)
