### ISSUE TITLE
[Uptime Billing] Unable to set an uptime budget for orgs using on-demand instead of PAYG

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#85437]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have an org that uses On-Demand instead of PAYG
2. Configure the On-Demand budget to have a nonzero amount for "Uptime monitors", and keep the rest of the categories at $1
3. Save the changes

### Expected Result

A new on-demand budget is set that allows the org to have more uptime monitors.

### Actual Result

We receive the notification "Budget turned off":
![Image](https://github.com/user-attachments/assets/d15fae5b-6495-4a68-9153-bc68c6f8e41d)

This points to [this logic](https://github.com/getsentry/getsentry/blob/1803111253ace5c50680ad3e7392b86d803c172c/static/getsentry/gsApp/views/onDemandBudgets/onDemandBudgetEditModal.tsx#L155-L159) which prints “budget turned off” when all on-demand values are set to $0. It looks like while the uptime monitor category has been added in the UI, the old on-demand doesn’t consider it for this part of the logic, and looks at only the other values, which in this case remain $0.

Adding $1 to ie. the "Errors" category seems to allow us to set one additional uptime monitor, but not a third one. Trying to do so throws a "Y" error.
![Image](https://github.com/user-attachments/assets/e24338d5-739e-42e9-bfa4-4ed5cd4b2eba)

Affected org in the [shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2398).

### Product Area

Settings - Subscription

**Comment by brianthi** [comment]
Bug fix in progress. @vbro will update this ticket when it ships.

**Comment by vbro** [comment]
Fix merged and deployed.

**Comment by InterstellarStella** [comment]
@brianthi @vbro It looks like the issue still exists. The customer has set a budget of $2, but they're only allowed to set up one additional monitor.
```
400 on PUT https://us.sentry.io/api/0/projects/org_slug/public/uptime/165162/ with error:

{
"status": "You don't have enough on-demand available to create a new monitor"
}
```

**Comment by vbro** [comment]
> It looks like the issue still exists

This is a separately issue and I created https://github.com/getsentry/sentry/issues/85863 to address it

**Comment by vbro** [comment]
FYI: original issue fixed with https://github.com/getsentry/getsentry/pull/16551
