### ISSUE TITLE
"resolved in the next release" not working as expected

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#88976]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Customer is experiencing this issue with their iOS project, currently using fastlane plugin and verified correct semantic versioning per our [docs](https://docs.sentry.io/platforms/javascript/configuration/releases/#bind-the-version).

Try to select "resolved in next release" for an issue from the latest release version for say version 4.6.1 (5)

### Expected Result

After selecting "resolved in next release" for an issue in version 4.6.1 (5) for the activity feed to show that it has been set as resolved in releases "greater than 4.6.1 (5)".

### Actual Result

Instead the activity feed shows that it has been set as resolved in releases "greater than 4.6.1 (2)" which is the wrong release. 

This then means that the next time this issue occurs in 4.6.1 (5) it is immediately marked as a regression, which is correct since the "resolved in next release" version is incorrect at 4.6.1 (2). 

Sentry appears to recognize that 4.6.1 (5) is > than 4.6.1 (2) because it is re-opening the issue, it just doesn't seem to be able to pick the right one when marking "resolved in next release".

Example links and additional details in internal ticket [#148963](https://sentry.zendesk.com/agent/tickets/148963)

<img width="661" alt="Image" src="https://github.com/user-attachments/assets/9f549404-bcc6-498e-8f95-2101b113b2b2" />

### Product Area

Releases

**Comment by leedongwei** [comment]
Will route internally to the correct team.

**Comment by bruno-garcia** [comment]
Thanks for reporting. Seems wrong indeed. We'll investigate this. 
cc @cmanallen

**Comment by cmanallen** [comment]
@ReneGreen27 I believe this is happening because the customer's releases are not being associated to a project.  Could you ask them how they're using the fastlane plugin?  Specifically what project slugs they're providing.

@bruno-garcia It seems weird that our release attribution process depends on a value that might not be provided.  This seems like a rather serious hole in the product.

**Comment by bruno-garcia** [comment]
Releases are not associated to projects, they are org wide. Events have `release` field, which by convention is `appname@version`, and different "apps" are often in different projects. But that's all conventions. Creating releases via a plugin (or sentry-cli which is usually what happens under the hood of these plugins) is optional. We definitely had issues where the plugin is creating a release with name `app@1.0.0` and the event sent by the SDK is just `release=1.0.0` , or the inverse, and then things don't match properly in Sentry. `release` in the event is also optional, and some SDKs don't send anything by default (JS for example). But most other SDKs always set a value because the framework providers hooks and ways to manage releases.

**Comment by cmanallen** [comment]
@bruno-garcia I'm talking specifically about this code: https://github.com/getsentry/sentry/blob/master/src/sentry/api/helpers/group_index/update.py#L814-L818.  Its requires releases be associated with a project so it can determine if that project is using semver or not.

I can find some (but not many) releases where the release date does not match the semver ordering.  That's my current theory as to why this is happening.

**Comment by bruno-garcia** [comment]
If releases are org-wide, I dunno how that code works by looking at releases per project

**Comment by cmanallen** [comment]
@bruno-garcia Releases are associated to projects through the ReleaseProject model.  Its many-to-one.  They take the project-id from the issue and try to find releases for the project.  They use those projects to determine if the releases are semver or not and then make a decision about what to do next.

There are lots of "HACK" and "TODO" style comments in the code.  I don't think this feature was very well thought out.  It seems like releases were project scoped in the past, then became org-scoped, and then this particular function found itself in a weird situation in regards to the data model.

There may be another bug here but its pretty difficult to parse all the code and the amount of state and specifically point-in-time state make this really difficult to debug.

**Comment by cmanallen** [comment]
If the customer can associate with one or more projects (via the cli) I think this issue would resolve itself for them.  There would be a time delay as new releases need to be created with the project association.  Unless there's an update endpoint but I've not looked for one.

**Comment by lukeredpath** [comment]
I am the original reporter of this issue. We create our Sentry releases using the fastlane plugin as part of the our release process. We call `sentry_create_release` with the project slug, app ID, version and build numbers. Following this, we also call `sentry_set_commits`, `sentry_upload_dsym` and finally we create a deployment record that indicates the release was deployed to TestFlight.

Once the build has passed QA we run a separate fastlane task to submit the app to the App Store. At this point we create a new sentry deploy record to indicate it has been deployed to the App Store, and call `sentry_finalize_release` to mark the release as final. So only the final release build that gets submitted should be marked as finalised.

I'm not aware of any way of associating releases with projects - I assumed that was the plugin's job (as we do pass the project slug).

**Comment by cmanallen** [comment]
@lukeredpath Hey Luke, thanks for reaching out.  I'll familiarize myself with our fastlane plugin and see whats going on.  Judging by the workflow you outlined above there's probably not an issue with your usage of the plugin.  It's possible there's an issue with our fastlane plugin but I doubt it.  It's likely somewhere in our back-end.

I'll use the workflow you outlined to reproduce the issue on my end.

**Comment by cmanallen** [comment]
@lukeredpath I noticed that releases begin populating for the `community-ios` project on April 17 with the first release being `4.7.0`.  When using the "resolved in next release" feature do you still observe the attribution issues or has it been resolved for issues in releases >= 4.7.0?

**Comment by lukeredpath** [comment]
@cmanallen we have releases dating way back before then. You're probably just seeing the non-archived releases.]

We are in the process of shipping a new release right now so I will need to wait until that is shipped and finalised in Sentry so I can see what happens if I mark as resolved in the next release.

**Comment by lukeredpath** [comment]
@cmanallen just confirming this is still an issue.

We had an issue in our latest published release, 4.10.0 (2), which will be resolved in the next release we ship, so I marked as "resolved in the next release". However it says this:

<img width="321" height="80" alt="Image" src="https://github.com/user-attachments/assets/18933373-8233-422e-a179-451d17fa06a8" />

Which is wrong, and means if the bug occurs again in the current release it will re-open the issue.

**Comment by cmanallen** [comment]
@lukeredpath Thanks for confirming.  Sorry this is still happening.  I'll take another look at this and see whats going on.

**Comment by simonmcl** [comment]
Hi, just to add that i'm experiencing this issue also, on a semi-regular basis. As you can see from the below screenshot. On the right this bug came on on v1.2.6. I fixed it and uploaded 1.2.7 to the app store for review. I came back to mark as resolved in next version and it shows that 1.2.5 is the current version

<img width="1134" height="303" alt="Image" src="https://github.com/user-attachments/assets/5c731d14-967c-4564-9972-12d8dbfa7a20" />


I'm not using the fastlane plugin. I have my own script where I use the CLI to upload the dsym's that I care about

**Comment by simonmcl** [comment]
The web-app updated today to a new design, with a popup asking me to take a tour. After I was done, I noticed that "the current release" is now lower than it was yesterday. Yesterday I marked a bug as fixed in current and the value was 1.2.9. Today is reversed back to 1.2.4. Lower than the previous screenshot of 1.2.5. And lower than the "first seen" on the right hand side of 1.2.9

<img width="1153" height="193" alt="Image" src="https://github.com/user-attachments/assets/b9a6904d-ad94-4f66-92e9-41a1fe873bd3" />

**Comment by cmanallen** [comment]
Hi @simonmcl.  Are you able to link the sentry issue?  I'll be able to investigate this more directly that way.

**Comment by cmanallen** [comment]
@simonmcl Do you know if you filtered by environment prior to visiting that issue? Or if you applied other filters on the issues browse page before clicking into the issue where you saw the current release as the wrong value?

**Comment by cmanallen** [comment]
@simonmcl I've found the source of your bug.  The releases are being sorted by the date they were created not by the semver value.  `1.2.4 (381)` was created after `1.2.9+391` which is why it appeared as the "current release".  Since then the 1.3 series has been released and has replaced 1.2.4 as the current release.

An obvious fix for this would be to sort by semver not date created.  But I'll need to figure out a way to support customers who do not use semver.

**Comment by simonmcl** [comment]
@cmanallen how/when is a release created? I've not done anything on my side with 1.2.4 for several weeks. Possible the first issue just came in from 1.2.4, is that when releases are created?

**Comment by cmanallen** [comment]
@simonmcl Releases are created in a couple different ways.  The two main ways are: manual creation using sentry-cli and automatic creation from SDK events.  So if someone used `1.2.4 (381)` for the first time or encountered an error or emitted a span Sentry would have created that release automatically for you.

**Comment by simonmcl** [comment]
@cmanallen ok then thats my issue, my CI script is not creating a release with the cli, as I didn't know it needed too, and they are all coming in out of order due to quick turn around on features/fixes. Could you provide me with a sample (or link to one) of how to create a release with the cli?

**Comment by cmanallen** [comment]
@simonmcl [These are our docs](https://docs.sentry.io/cli/) which are pretty great at getting you setup.  We also have some plugins for maven, fastlane, JavaScript bundler, etc. which can help simplify the process.  Let me know if you have any trouble setting it up.

But my hope is that you do this because you want to not because you have to. I think this semver sorting issue could and should be fixed. I'll hopefully be getting to it soon.

**Comment by simonmcl** [comment]
@cmanallen Its now picking up the manual releases from the CLI, thanks

I'm also adding the CLI updates as waiting for an event to come in doesn't suit my flow, even if the semver issue was fixed. I like to be able to mark them as resolved when I push to the app store review, which often seems to have not generated an event by then. Having it always there after the CI run suits me better

**Comment by cmanallen** [comment]
@simonmcl That's great to hear.  I agree I think it's a much better product experience that way.  Glad you're finding value.

**Comment by masinette** [comment]
Related to: https://sentry.zendesk.com/agent/tickets/168927

**Comment by jeffremer** [comment]
Hi there 👋 I regularly encounter this problem and it creates a lot of noise and uncertainty with respect to tracking fixed crashes.

1. Say a crash is present in 1.1
2. I fix the crash in 1.2 and mark it as resolved in Sentry
3. Someone encounters the crash on 1.1 and that reopens the crash as a regression in Sentry
4. We get Slack alert noise, I have to into Sentry and make sure it was actually an old crash or not

This sort of makes the resolution feature useless (unless we're lucky and the crash never shows up again in an older version due to adoption, but that never happens or takes a while).

We use the fastlane plugin to ship dSYMs to Sentry, `sentry_debug_files_upload` - so I'm not entirely sure if recording the release in Sentry another way would mitigate this or not.

Anyway, thanks for the help! I'd love to get this feature working so we can reduce the noise and uncertainty.

**Comment by Kobby-Bawuah** [comment]
Another customer is experiencing this same issue with their iOS project. Their releases are sent as bare version strings (e.g., 5.36.2) without the package@version format, which causes Release.is_semver_version() to return False (line 368 of release.py — the "@" not in version check). This forces follows_semver_versioning_scheme() to return False at line 914 even if the project's recent releases would otherwise pass the semver heuristic.

As a result, the "resolve in next release" flow enters the non-semver/date-based path in process_group_resolution (lines 577–622 of update.py), which rewrites in_next_release to in_release with the current version. 

The UI briefly shows "upcoming release" but reverts to the current version after refetch, making it look like the selection didn't stick. The activity feed confirms this with all resolutions labeled (non-semver) and regressions noted as "compared via release date".

This creates a resolve → immediate regression loop for them on every release cycle.

ZD ticket: https://sentry.zendesk.com/agent/tickets/178948

**Comment by minori-fh** [comment]
Another example of release-ordering/regression behavior being impacted by client-supplied release values.: A customer had a client-supplied release (999.9.9) created from a modified/sideloaded app. Because it is valid semver and sorts above their legitimate releases, it appears to become the project's greatest release baseline and prevents issues resolved in a release from reopening/regressing as expected.

**Comment by souredoutlook** [comment]
@minori-fh we've got two PRs up to address the example you've shared here: 

Backend: https://github.com/getsentry/sentry/pull/117785
Frontend: https://github.com/getsentry/sentry/pull/117786

**Comment by souredoutlook** [comment]
For anyone else experiencing issues like what is described here: https://github.com/getsentry/sentry/issues/88976#issuecomment-3608705722

Specifically:

> Someone encounters the crash on 1.1 and that reopens the crash as a regression in Sentry
We get Slack alert noise, I have to into Sentry and make sure it was actually an old crash or not

We're introducing some new concepts around fix progress that may be of interest to you. If you're resolving Sentry issues in your commits, prs and releases (especially if you're doing this with agents) and want to hear more about what's coming - please reach out at nicholas.meisenheimer@sentry.io
